// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/faucet": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/.well-known/appspecific/com.chrome.devtools.json" | "/faucet";
  };
  "routes/chrome-devtools-probe.ts": {
    id: "routes/chrome-devtools-probe";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/faucet.tsx": {
    id: "routes/faucet";
    page: "/faucet";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/chrome-devtools-probe": typeof import("./src/routes/chrome-devtools-probe.ts");
  "routes/faucet": typeof import("./src/routes/faucet.tsx");
  "routes/index": typeof import("./src/routes/index.tsx");
};